# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tcr < Formula
  desc ""
  homepage "https://github.com/jaedle/homebrew-test-and-commit-or-revert"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaedle/test-and-commit-or-revert/releases/download/v0.1.2/test-and-commit-or-revert_Darwin_x86_64.tar.gz"
      sha256 "350da5ed464b2ecc7b781d6c27be1a94050149de39fa877f6b275d8992c7f8e9"

      def install
        bin.install "test-and-commit-or-revert"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaedle/test-and-commit-or-revert/releases/download/v0.1.2/test-and-commit-or-revert_Darwin_arm64.tar.gz"
      sha256 "484807b40b682ec1d46a33d32b776a4d33f9898fcbc7f77b0e6cc0df4b21ea11"

      def install
        bin.install "test-and-commit-or-revert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaedle/test-and-commit-or-revert/releases/download/v0.1.2/test-and-commit-or-revert_Linux_arm64.tar.gz"
      sha256 "6cb73bdc2792a8c06fd1f0f3a24a37a2ec2492540090e0842ebc001eb598a7e6"

      def install
        bin.install "test-and-commit-or-revert"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaedle/test-and-commit-or-revert/releases/download/v0.1.2/test-and-commit-or-revert_Linux_x86_64.tar.gz"
      sha256 "25dc59b55084bf5c618ccc33088208e24b6770fd705eabc91e8da66f07eac804"

      def install
        bin.install "test-and-commit-or-revert"
      end
    end
  end
end
