# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestAndCommitOrRevert < Formula
  desc ""
  homepage "https://github.com/jaedle/homebrew-test-and-commit-or-revert"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaedle/test-and-commit-or-revert/releases/download/v0.1.3/tcr_Darwin_arm64.tar.gz"
      sha256 "9cd99e982fdfedfd731dc65bc46009c66c02e4f33369296e80fe83e789f3f91c"

      def install
        bin.install "tcr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaedle/test-and-commit-or-revert/releases/download/v0.1.3/tcr_Darwin_x86_64.tar.gz"
      sha256 "e542a7ecf46ce3ca85d5c5416f061814d8ddd37a7a2b8fc6aaecb4d21f137131"

      def install
        bin.install "tcr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaedle/test-and-commit-or-revert/releases/download/v0.1.3/tcr_Linux_arm64.tar.gz"
      sha256 "10570e1a454e1b3cc84f4d78bb67d9a9f8c8efb1180ccb5f1e154f82504b3e15"

      def install
        bin.install "tcr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaedle/test-and-commit-or-revert/releases/download/v0.1.3/tcr_Linux_x86_64.tar.gz"
      sha256 "f73f1e1d8509db9aedfab8fe1ac5f14f2eb525f4868bee4ac76c4dc43c0f3939"

      def install
        bin.install "tcr"
      end
    end
  end
end
